export const ADD = "ADD";
export const XMPP_CONNECT = "XMPP_CONNECT";
export const XMPP_SEND_MESSAGE = "XMPP_SEND_MESSAGE";
export const XMPP_RECEIVE_MESSAGE = "XMPP_RECEIVE_MESSAGE";
export const CHAT_GET_CHATLIST = "CHAT_GET_CHATLIST";
export const CHAT_GO_ROOM = "CHAT_GO_ROOM";
export const CHAT_DELETE_CELL = "CHAT_DELETE_CELL";

